# Generated by Django 2.2.14 on 2021-07-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210731_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='active',
        ),
    ]
