# Generated by Django 2.2.14 on 2021-07-31 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_todo_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='oser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
