# Generated by Django 2.2.14 on 2021-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20210731_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
