# Generated by Django 2.2.14 on 2021-08-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todo_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='details',
        ),
    ]
